"""Checklist of every Pop! Pokémon entry (from Pop Shop Guide + known releases)."""

# Each: (number, name, version, exclusive)
# version/exclusive empty string when none.
CHECKLIST: list[tuple[int, str, str, str]] = [
    (353, "Pikachu", "", "Target"),
    (353, "Pikachu", "Flocked", "GameStop"),
    (353, "Pikachu", "10 inch", "Target"),
    (353, "Pikachu", "Metallic", ""),
    (353, "Pikachu", "10 inch Metallic", "Target Con 2021"),
    (353, "Pikachu", "Pearlescent", "Pokémon Center"),
    (353, "Pikachu", "Soft Color", "Funko Shop"),
    (453, "Bulbasaur", "", ""),
    (453, "Bulbasaur", "Flocked", "ECCC 2020 / Amazon"),
    (453, "Bulbasaur", "Diamond Collection", "FunKon Summer SDCC 2021 / Target"),
    (453, "Bulbasaur", "Metallic", ""),
    (453, "Bulbasaur", "Pearlescent", "Pokémon Center"),
    (453, "Bulbasaur", "Soft Color", "Amazon"),
    (454, "Bulbasaur", "10 inch", "Target"),
    (454, "Bulbasaur", "10 inch Metallic", "Target"),
    (455, "Charmander", "", ""),
    (455, "Charmander", "Flocked", "ECCC 2020 / Walmart"),
    (455, "Charmander", "Diamond Collection", "ECCC 2021 / Target"),
    (455, "Charmander", "Silver Metallic", ""),
    (455, "Charmander", "Metallic", "SDCC 2022 / FYE"),
    (455, "Charmander", "Pearlescent", "Pokémon Center"),
    (455, "Charmander", "Soft Color", "Amazon"),
    (456, "Charmander", "10 inch", "Target"),
    (504, "Squirtle", "", ""),
    (504, "Squirtle", "Flocked", "GameStop"),
    (504, "Squirtle", "Diamond Collection", "FunKon Summer SDCC 2021 / GameStop"),
    (504, "Squirtle", "Metallic", ""),
    (504, "Squirtle", "Pearlescent", "Pokémon Center"),
    (504, "Squirtle", "Soft Color", "BoxLunch"),
    (505, "Squirtle", "10 inch", "Target"),
    (540, "Eevee", "10 inch", "Target"),
    (553, "Pikachu", "Waving", ""),
    (553, "Pikachu", "Waving Diamond Collection", "GameStop"),
    (553, "Pikachu", "Waving Flocked", "Zavvi"),
    (577, "Eevee", "", ""),
    (577, "Eevee", "Flocked", "WonderCon 2020 / Hot Topic"),
    (577, "Eevee", "Pearlescent", "Pokémon Center"),
    (579, "Pichu", "", ""),
    (579, "Pichu", "Flocked", "WonderCon 2020 / FYE"),
    (579, "Pichu", "Pearlescent", "Pokémon Center"),
    (580, "Vulpix", "", ""),
    (580, "Vulpix", "Flocked", "SDCC 2020 / GameStop"),
    (580, "Vulpix", "Pearlescent", "Pokémon Center"),
    (581, "Mewtwo", "", ""),
    (581, "Mewtwo", "Flocked", "SDCC 2020 / Funko Shop"),
    (581, "Mewtwo", "Pearlescent", "Pokémon Center"),
    (582, "Mr. Mime", "", ""),
    (583, "Mewtwo", "10 inch", "Target"),
    (595, "Rattata", "", ""),
    (596, "Cubone", "", ""),
    (596, "Cubone", "Pearlescent", "Pokémon Center"),
    (597, "Growlithe", "", ""),
    (597, "Growlithe", "Flocked", "NYCC 2020 / BoxLunch"),
    (598, "Pikachu", "Grumpy", ""),
    (598, "Pikachu", "Grumpy Flocked", "NYCC 2020 / Target"),
    (599, "Vulpix", "10 inch", "Target"),
    (619, "Cubone", "10 inch", "Target"),
    (626, "Eevee", "", ""),
    (626, "Eevee", "Diamond Collection", "NYCC 2021 / Hot Topic"),
    (627, "Vaporeon", "", ""),
    (627, "Vaporeon", "Diamond Collection", "ECCC 2021 / Barnes & Noble"),
    (627, "Vaporeon", "Pearlescent", "Pokémon Center"),
    (628, "Jolteon", "", ""),
    (628, "Jolteon", "Diamond Collection", "WonderCon 2021 / BoxLunch"),
    (628, "Jolteon", "Pearlescent", "Pokémon Center"),
    (629, "Flareon", "", ""),
    (629, "Flareon", "Diamond Collection", "WonderCon 2021 / FYE"),
    (629, "Flareon", "Pearlescent", "Pokémon Center"),
    (643, "Mew", "", ""),
    (644, "Ponyta", "", ""),
    (645, "Raichu", "", ""),
    (645, "Raichu", "Pearlescent", "Pokémon Center"),
    (779, "Pikachu", "Attack Stance", ""),
    (780, "Meowth", "", ""),
    (781, "Psyduck", "", ""),
    (842, "Pikachu", "Sitting", ""),
    (842, "Pikachu", "Sitting Diamond Collection", "ECCC 2021 / Target"),
    (843, "Charizard", "", ""),
    (844, "Horsea", "", ""),
    (848, "Caterpie", "", ""),
    (849, "Pidgeotto", "", ""),
    (850, "Dragonite", "", ""),
    (851, "Charizard", "10 inch", "Target"),
    (852, "Mew", "10 inch", "Target"),
    (855, "Alakazam", "", ""),
    (856, "Lucario", "", ""),
    (856, "Lucario", "Pearlescent", "Pokémon Center"),
    (857, "Sylveon", "", ""),
    (863, "Lucario", "10 inch", "Target Con 2022"),
    (864, "Lapras", "", ""),
    (864, "Lapras", "Pearlescent", "Pokémon Center"),
    (865, "Piplup", "", ""),
    (865, "Piplup", "Pearlescent", "Pokémon Center"),
    (866, "Leafeon", "", ""),
    (867, "Lapras", "10 inch", "Target"),
    (884, "Espeon", "", ""),
    (884, "Espeon", "Flocked", "Amazon"),
    (885, "Munchlax", "", ""),
    (886, "Oshawott", "", ""),
    (917, "Munchlax", "10 inch", "Target Con 2023"),
    (920, "Arcanine", "", ""),
    (921, "Glaceon", "", ""),
    (921, "Glaceon", "Flocked", "Hot Topic"),
    (922, "Scorbunny", "", ""),
    (930, "Glaceon", "10 inch", "Target"),
    (940, "Arceus", "10 inch", "SDCC 2024 / GameStop"),
    (947, "Aipom", "", ""),
    (947, "Aipom", "Flocked", "Specialty Series"),
    (948, "Umbreon", "", ""),
    (948, "Umbreon", "Flocked", "Chalice Collectibles"),
    (949, "Sobble", "", ""),
    (950, "Umbreon", "10 inch", "Target Con 2024"),
    (951, "Pikachu", "18 inch", ""),
    (956, "Luxray", "", ""),
    (957, "Grookey", "", ""),
    (957, "Grookey", "Flocked", "Amazon"),
    (958, "Wooloo", "", ""),
    (959, "Luxray", "10 inch", "Target"),
    (963, "Chimchar", "", ""),
    (963, "Chimchar", "Flocked", "Funko Shop"),
    (964, "Snubbull", "", ""),
    (965, "Cresselia", "10 inch", "C2E2 2024 / Barnes & Noble"),
    (968, "Greninja", "", ""),
    (980, "Greninja", "10 inch", "Target"),
    (983, "Blaziken", "", ""),
    (984, "Sprigatito", "", ""),
    (985, "Teddiursa", "", ""),
    (996, "Dialga", "10 inch", "NYCC 2024 / GameStop"),
    (997, "Palkia", "10 inch", "FunKon London 2024 / Target"),
    (1011, "Alolan Raichu", "", ""),
    (1012, "Quaxly", "", ""),
    (1013, "Mimikyu", "", ""),
    (1014, "Sprigatito", "10 inch", "Target"),
    (1020, "Mimikyu", "10 inch", "Target"),
    (1030, "Fuecoco", "", ""),
    (1031, "Gengar", "", ""),
    (1032, "Zorua", "", ""),
    (1048, "Suicune", "10 inch", "WonderCon 2025 / Amazon"),
    (1049, "Gengar", "10 inch", "Target"),
    (1050, "Dratini", "", ""),
    (1051, "Fidough", "", ""),
    (1052, "Gardevoir", "", ""),
    (1068, "Gardevoir", "10 inch", "Target"),
    (1070, "Entei", "10 inch", "SDCC 2025 / Entertainment Earth"),
    (1076, "Ceruledge", "", ""),
    (1077, "Slowpoke", "", ""),
    (1078, "Turtwig", "", ""),
    (1088, "Slowpoke", "10 inch", "Target"),
    (1090, "Absol", "", ""),
    (1091, "Ninetales", "", ""),
    (1092, "Rowlet", "", ""),
    (1104, "Raikou", "10 inch", "NYCC 2025 / Amazon"),
    (1107, "Ninetales", "10 inch", "Target Funko Friday"),
    (1149, "Ceruledge", "10 inch", "Target"),
    # Recent / shop-only lines seen on Funko.com (may pre-date checklist updates)
    (0, "Charmeleon", "Jumbo", ""),
    (0, "Zoroark", "", ""),
    (0, "Goomy", "", ""),
    (0, "Teddiursa", "", ""),
    (0, "Absol", "", ""),
    (0, "Charmander", "Soft Color", ""),
    (0, "Bulbasaur", "Soft Color", ""),
    (0, "Squirtle", "Soft Color", ""),
    (0, "Pikachu", "Soft Color", ""),
    (0, "Grookey", "", ""),
    (0, "Sobble", "", ""),
    (0, "Gardevoir", "Jumbo", ""),
    (0, "Ninetales", "Jumbo", ""),
    (0, "Munchlax", "Jumbo", ""),
]

COMBO_PACKS = [
    ("Eevee Evolution 4-Pack", "Eevee, Vaporeon, Jolteon, Flareon"),
    ("Kanto Starters 4-Pack", "Pikachu, Bulbasaur, Charmander, Squirtle"),
]

MOMENTS = [
    (1, "Bulbasaur / Charmander / Squirtle", "Pokémon 1996 Deluxe"),
]
